aiken-lang/site

src/pages/language-tour/control-flow.mdx

Fix typo on if-else in control-flow

Fix typo on if-else in control-flow

---

src/pages/language-tour/custom-types.mdx

fix typo on custom-types.mdx

---

src/pages/language-tour/custom-types.mdx
src/pages/language-tour/functions.mdx
src/pages/language-tour/primitive-types.mdx

Depends on aiken-lang/aiken#255

Remove leading '#' on tuples.

---

src/pages/getting-started/hello-world.mdx
src/pages/getting-started/vesting.mdx

Related to aiken-lang/aiken#316

Rework the user guide tutorials to make use of the Plutus blueprint.

---

src/pages/fundamentals/eutxo.mdx

Just a couple minor things I noticed while reading the EUTxO Crash Course.

minor typo fixes

---

pnpm-lock.yaml
src/pages/_meta.json
src/pages/example--gift-card.mdx
src/pages/example--vesting.mdx
src/pages/fundamentals/eutxo.mdx
src/pages/index.mdx
src/pages/language-tour/modules.mdx

This is a tutorial for the gift card example found in the main aiken repo
https://github.com/aiken-lang/aiken/tree/main/examples/gift_card
closes https://github.com/aiken-lang/aiken/issues/461

Gift Card tutorial

---

src/pages/language-tour/custom-types.mdx

Removing the .md from the link to make it work correctly.

Fixing broken link

---

src/pages/example--hello-world.mdx
src/pages/fundamentals/eutxo.mdx
src/pages/language-tour/control-flow.mdx
src/pages/language-tour/custom-types.mdx
src/pages/language-tour/functions.mdx
src/pages/language-tour/modules.mdx
src/pages/language-tour/primitive-types.mdx
src/pages/language-tour/tests.mdx
src/pages/language-tour/troubleshooting.mdx

grammar fixes (including correcting English) + clarifications (mostly minor)

grammar fixes + clarifications (mostly minor)

---

.gitignore
package.json
pnpm-lock.yaml
src/pages/example--vesting.mdx

Also bumped the version of the sharp package because I was having issues on WSL.

Little improvements to vesting example code snippets

---

src/pages/example--vesting.mdx

This PR implements the improvements discussed in #51 for the vesting example.

Fix vesting example

---

src/pages/fundamentals/getting-started.mdx

Fixed typo

---

src/pages/example--hello-world/basics.mdx
src/pages/example--hello-world/end-to-end/lucid.mdx
src/pages/language-tour/custom-types.mdx
src/pages/language-tour/tests.mdx

Some of the changes might be matters of opinion, so please take them as mere suggestions 🙂

Fix Some Typos

---

src/pages/language-tour/primitive-types.mdx

This doesn't seem to be mentioned anywhere (I myself found it in the [Discord server](https://discord.com/channels/946071061567529010/967217093688836137/1124056017307705385)), although I'm not sure where is the best place to include it.

Add Note About Laziness of `&&` and `||`

---

src/pages/example--gift-card.mdx
src/pages/example--hello-world/basics.mdx
src/pages/example--hello-world/end-to-end/pycardano.mdx

going through the tutorials and updating things in preparation for the plutus v3 changes

update to v3 syntax

---

src/pages/language-tour/troubleshooting.mdx

Update `?` operator docs

---

src/pages/example--hello-world/end-to-end/_meta.json
src/pages/example--hello-world/end-to-end/mesh.mdx
src/pages/resources.mdx

@KtorZ, I made a few changes here:
- update hello world tutorial to use `MeshTxBuilder` instead of `Transaction` for future proofing
- after Chang, reference script fee calculation requires fetcher
- use TypeScript instead
- added a link to the code example so anyone and test
- remove tangocrypto, its not live anymore

update hello world tutorial

---

src/pages/example--gift-card.mdx

added Option to spend handler &
change transaction -> tx
let Transaction { mint, inputs, .. } = tx

Gift Card = added Option to spend handler & change transaction-> tx

---

src/pages/language-tour/modules.mdx

This matters when we're dealing with CBOR.

Opaque types: newtype

---

src/pages/example--vesting/mesh.mdx

This change is required to avoid `ConwayUtxowFailure (UtxoFailure (BabbageOutputTooSmallUTxO ...` error.

fix: specify missing txOut amount

---

src/pages/example--hello-world/end-to-end/pycardano.mdx

Just a couple minor changes I made to get the hello world tutorial working today with PyCardano v0.14.

Fix hello world pycardano
